### PR TITLE
SIM: modify id and offset for Ecal and Hcal

### PR DESCRIPTION
**Pull request by fucd**
* HcalBarrel has vary offset by layers, use TiledLayerGridXY now
* HcalEndcaps + HcalEndcapRing
  * x:y id is rotated in different quadrant, exchange them x<->y while saving data (set in segmentation `y:32:-16,x:-16`) to keep same as Mokka's

### CODE REVIEW

**Comment by wenxingfang** [comment]
Hi @fucd ,

Thanks! How about the offset in SEcal05_siw_Endcaps.xml, will you update that also ?

Best,
Wenxing

**Comment by fucd** [comment]
@wenxingfang 
Only offset difference is believable to affect very tiny on physics, it can be updated later.

**Comment by wenxingfang** [comment]
Hi @fucd 

From my previous study, I found the offset will affect physics performance obviously. I don't know if it is easy for you to update the offset for Ecal Endcap, then I can test the Ecal Endcap and ring at same time. By the way, did you checked if the cell center is the same with Mokkas when using you updated xml files? such as the cell center for Ecal Ring Hcal Barrel and others?

**Comment by fucd** [comment]
@wenxingfang 
I think offset's effect is not physical. I guess id is more important since the reconstruction need to find cell's neighbor. Do you know how PFA find neighbor? I can not understand how offset affect on performance. Or do you plan to update PFA method to DD4hep?
Currently, I have try to make the cell centers of HcalBarrel, HcalEndcaps and HcalEndcapRing same as Mokka.
Of course, I will continue to update Ecal. Before ready, I think you can focus on others.

**Comment by wenxingfang** [comment]
Hi @fucd ,
As the offset will effect the center of cell (or digi hit position), so it will affect the reconstruction performance (at least from my previous pandora study). Actually, for pandora the cell id is only used for getting the layer and stave number of digi hit, so as only as layer and stave number are correct, it is fine. The neighbor finding in pandora will use the digi hit position. I have already updated the pandora code for using geo info from DD4HEP.  
I agree with you that we can  focus on Hcal now and update the Ecal offset later.

**Pull request merged**
